# Generated by Django 3.1.7 on 2021-04-08 13:43

from django.conf import settings
from django.db import migrations, models
import user_profile.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='user_likes',
            field=models.ManyToManyField(blank=True, default=user_profile.models.CustomUser, to=settings.AUTH_USER_MODEL),
        ),
    ]
