# Generated by Django 3.1.7 on 2021-04-06 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_post_display_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_pic',
            field=models.ImageField(null=True, upload_to='post_img/'),
        ),
    ]
