<<<<<<< HEAD
# Generated by Django 3.1.7 on 2021-04-12 15:20
# Generated by Django 3.1.7 on 2021-04-12 14:40
=======
# Generated by Django 3.2 on 2021-04-12 21:55
>>>>>>> 5e384102c28930b27f4ed4ea926321d09228842d

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read', models.BooleanField(default=False)),
                ('reciever', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reciever', to=settings.AUTH_USER_MODEL)),
                ('text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_notify', to='post.post')),
            ],
        ),
    ]
